// flow-typed signature: 3f13d289fadba4943d8433af5f2dc43e
// flow-typed version: <<STUB>>/antlr4_v^4.7.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'antlr4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'antlr4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'antlr4/atn/ATN' {
  declare module.exports: any;
}

declare module 'antlr4/atn/ATNConfig' {
  declare module.exports: any;
}

declare module 'antlr4/atn/ATNConfigSet' {
  declare module.exports: any;
}

declare module 'antlr4/atn/ATNDeserializationOptions' {
  declare module.exports: any;
}

declare module 'antlr4/atn/ATNDeserializer' {
  declare module.exports: any;
}

declare module 'antlr4/atn/ATNSimulator' {
  declare module.exports: any;
}

declare module 'antlr4/atn/ATNState' {
  declare module.exports: any;
}

declare module 'antlr4/atn/ATNType' {
  declare module.exports: any;
}

declare module 'antlr4/atn/index' {
  declare module.exports: any;
}

declare module 'antlr4/atn/LexerAction' {
  declare module.exports: any;
}

declare module 'antlr4/atn/LexerActionExecutor' {
  declare module.exports: any;
}

declare module 'antlr4/atn/LexerATNSimulator' {
  declare module.exports: any;
}

declare module 'antlr4/atn/ParserATNSimulator' {
  declare module.exports: any;
}

declare module 'antlr4/atn/PredictionMode' {
  declare module.exports: any;
}

declare module 'antlr4/atn/SemanticContext' {
  declare module.exports: any;
}

declare module 'antlr4/atn/Transition' {
  declare module.exports: any;
}

declare module 'antlr4/BufferedTokenStream' {
  declare module.exports: any;
}

declare module 'antlr4/CharStreams' {
  declare module.exports: any;
}

declare module 'antlr4/CommonTokenFactory' {
  declare module.exports: any;
}

declare module 'antlr4/CommonTokenStream' {
  declare module.exports: any;
}

declare module 'antlr4/dfa/DFA' {
  declare module.exports: any;
}

declare module 'antlr4/dfa/DFASerializer' {
  declare module.exports: any;
}

declare module 'antlr4/dfa/DFAState' {
  declare module.exports: any;
}

declare module 'antlr4/dfa/index' {
  declare module.exports: any;
}

declare module 'antlr4/error/DiagnosticErrorListener' {
  declare module.exports: any;
}

declare module 'antlr4/error/ErrorListener' {
  declare module.exports: any;
}

declare module 'antlr4/error/Errors' {
  declare module.exports: any;
}

declare module 'antlr4/error/ErrorStrategy' {
  declare module.exports: any;
}

declare module 'antlr4/error/index' {
  declare module.exports: any;
}

declare module 'antlr4/FileStream' {
  declare module.exports: any;
}

declare module 'antlr4/InputStream' {
  declare module.exports: any;
}

declare module 'antlr4/IntervalSet' {
  declare module.exports: any;
}

declare module 'antlr4/Lexer' {
  declare module.exports: any;
}

declare module 'antlr4/LL1Analyzer' {
  declare module.exports: any;
}

declare module 'antlr4/Parser' {
  declare module.exports: any;
}

declare module 'antlr4/ParserRuleContext' {
  declare module.exports: any;
}

declare module 'antlr4/polyfills/codepointat' {
  declare module.exports: any;
}

declare module 'antlr4/polyfills/fromcodepoint' {
  declare module.exports: any;
}

declare module 'antlr4/PredictionContext' {
  declare module.exports: any;
}

declare module 'antlr4/Recognizer' {
  declare module.exports: any;
}

declare module 'antlr4/RuleContext' {
  declare module.exports: any;
}

declare module 'antlr4/Token' {
  declare module.exports: any;
}

declare module 'antlr4/tree/index' {
  declare module.exports: any;
}

declare module 'antlr4/tree/Tree' {
  declare module.exports: any;
}

declare module 'antlr4/tree/Trees' {
  declare module.exports: any;
}

declare module 'antlr4/Utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'antlr4/atn/ATN.js' {
  declare module.exports: $Exports<'antlr4/atn/ATN'>;
}
declare module 'antlr4/atn/ATNConfig.js' {
  declare module.exports: $Exports<'antlr4/atn/ATNConfig'>;
}
declare module 'antlr4/atn/ATNConfigSet.js' {
  declare module.exports: $Exports<'antlr4/atn/ATNConfigSet'>;
}
declare module 'antlr4/atn/ATNDeserializationOptions.js' {
  declare module.exports: $Exports<'antlr4/atn/ATNDeserializationOptions'>;
}
declare module 'antlr4/atn/ATNDeserializer.js' {
  declare module.exports: $Exports<'antlr4/atn/ATNDeserializer'>;
}
declare module 'antlr4/atn/ATNSimulator.js' {
  declare module.exports: $Exports<'antlr4/atn/ATNSimulator'>;
}
declare module 'antlr4/atn/ATNState.js' {
  declare module.exports: $Exports<'antlr4/atn/ATNState'>;
}
declare module 'antlr4/atn/ATNType.js' {
  declare module.exports: $Exports<'antlr4/atn/ATNType'>;
}
declare module 'antlr4/atn/index.js' {
  declare module.exports: $Exports<'antlr4/atn/index'>;
}
declare module 'antlr4/atn/LexerAction.js' {
  declare module.exports: $Exports<'antlr4/atn/LexerAction'>;
}
declare module 'antlr4/atn/LexerActionExecutor.js' {
  declare module.exports: $Exports<'antlr4/atn/LexerActionExecutor'>;
}
declare module 'antlr4/atn/LexerATNSimulator.js' {
  declare module.exports: $Exports<'antlr4/atn/LexerATNSimulator'>;
}
declare module 'antlr4/atn/ParserATNSimulator.js' {
  declare module.exports: $Exports<'antlr4/atn/ParserATNSimulator'>;
}
declare module 'antlr4/atn/PredictionMode.js' {
  declare module.exports: $Exports<'antlr4/atn/PredictionMode'>;
}
declare module 'antlr4/atn/SemanticContext.js' {
  declare module.exports: $Exports<'antlr4/atn/SemanticContext'>;
}
declare module 'antlr4/atn/Transition.js' {
  declare module.exports: $Exports<'antlr4/atn/Transition'>;
}
declare module 'antlr4/BufferedTokenStream.js' {
  declare module.exports: $Exports<'antlr4/BufferedTokenStream'>;
}
declare module 'antlr4/CharStreams.js' {
  declare module.exports: $Exports<'antlr4/CharStreams'>;
}
declare module 'antlr4/CommonTokenFactory.js' {
  declare module.exports: $Exports<'antlr4/CommonTokenFactory'>;
}
declare module 'antlr4/CommonTokenStream.js' {
  declare module.exports: $Exports<'antlr4/CommonTokenStream'>;
}
declare module 'antlr4/dfa/DFA.js' {
  declare module.exports: $Exports<'antlr4/dfa/DFA'>;
}
declare module 'antlr4/dfa/DFASerializer.js' {
  declare module.exports: $Exports<'antlr4/dfa/DFASerializer'>;
}
declare module 'antlr4/dfa/DFAState.js' {
  declare module.exports: $Exports<'antlr4/dfa/DFAState'>;
}
declare module 'antlr4/dfa/index.js' {
  declare module.exports: $Exports<'antlr4/dfa/index'>;
}
declare module 'antlr4/error/DiagnosticErrorListener.js' {
  declare module.exports: $Exports<'antlr4/error/DiagnosticErrorListener'>;
}
declare module 'antlr4/error/ErrorListener.js' {
  declare module.exports: $Exports<'antlr4/error/ErrorListener'>;
}
declare module 'antlr4/error/Errors.js' {
  declare module.exports: $Exports<'antlr4/error/Errors'>;
}
declare module 'antlr4/error/ErrorStrategy.js' {
  declare module.exports: $Exports<'antlr4/error/ErrorStrategy'>;
}
declare module 'antlr4/error/index.js' {
  declare module.exports: $Exports<'antlr4/error/index'>;
}
declare module 'antlr4/FileStream.js' {
  declare module.exports: $Exports<'antlr4/FileStream'>;
}
declare module 'antlr4/index' {
  declare module.exports: $Exports<'antlr4'>;
}
declare module 'antlr4/index.js' {
  declare module.exports: $Exports<'antlr4'>;
}
declare module 'antlr4/InputStream.js' {
  declare module.exports: $Exports<'antlr4/InputStream'>;
}
declare module 'antlr4/IntervalSet.js' {
  declare module.exports: $Exports<'antlr4/IntervalSet'>;
}
declare module 'antlr4/Lexer.js' {
  declare module.exports: $Exports<'antlr4/Lexer'>;
}
declare module 'antlr4/LL1Analyzer.js' {
  declare module.exports: $Exports<'antlr4/LL1Analyzer'>;
}
declare module 'antlr4/Parser.js' {
  declare module.exports: $Exports<'antlr4/Parser'>;
}
declare module 'antlr4/ParserRuleContext.js' {
  declare module.exports: $Exports<'antlr4/ParserRuleContext'>;
}
declare module 'antlr4/polyfills/codepointat.js' {
  declare module.exports: $Exports<'antlr4/polyfills/codepointat'>;
}
declare module 'antlr4/polyfills/fromcodepoint.js' {
  declare module.exports: $Exports<'antlr4/polyfills/fromcodepoint'>;
}
declare module 'antlr4/PredictionContext.js' {
  declare module.exports: $Exports<'antlr4/PredictionContext'>;
}
declare module 'antlr4/Recognizer.js' {
  declare module.exports: $Exports<'antlr4/Recognizer'>;
}
declare module 'antlr4/RuleContext.js' {
  declare module.exports: $Exports<'antlr4/RuleContext'>;
}
declare module 'antlr4/Token.js' {
  declare module.exports: $Exports<'antlr4/Token'>;
}
declare module 'antlr4/tree/index.js' {
  declare module.exports: $Exports<'antlr4/tree/index'>;
}
declare module 'antlr4/tree/Tree.js' {
  declare module.exports: $Exports<'antlr4/tree/Tree'>;
}
declare module 'antlr4/tree/Trees.js' {
  declare module.exports: $Exports<'antlr4/tree/Trees'>;
}
declare module 'antlr4/Utils.js' {
  declare module.exports: $Exports<'antlr4/Utils'>;
}
