// flow-typed signature: 1f034b95072713e229fda581348719d3
// flow-typed version: <<STUB>>/fs-transaction_v^1.0.10/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-transaction'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-transaction' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fs-transaction/__test__/__test__fs-transaction' {
  declare module.exports: any;
}

declare module 'fs-transaction/__test__/__test__replaceTempPath' {
  declare module.exports: any;
}

declare module 'fs-transaction/build/errorTypes' {
  declare module.exports: any;
}

declare module 'fs-transaction/build/filenameUtils' {
  declare module.exports: any;
}

declare module 'fs-transaction/build/fs-transaction' {
  declare module.exports: any;
}

declare module 'fs-transaction/build/sequencePromise' {
  declare module.exports: any;
}

declare module 'fs-transaction/src/errorTypes' {
  declare module.exports: any;
}

declare module 'fs-transaction/src/filenameUtils' {
  declare module.exports: any;
}

declare module 'fs-transaction/src/fs-transaction' {
  declare module.exports: any;
}

declare module 'fs-transaction/src/sequencePromise' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fs-transaction/__test__/__test__fs-transaction.js' {
  declare module.exports: $Exports<'fs-transaction/__test__/__test__fs-transaction'>;
}
declare module 'fs-transaction/__test__/__test__replaceTempPath.js' {
  declare module.exports: $Exports<'fs-transaction/__test__/__test__replaceTempPath'>;
}
declare module 'fs-transaction/build/errorTypes.js' {
  declare module.exports: $Exports<'fs-transaction/build/errorTypes'>;
}
declare module 'fs-transaction/build/filenameUtils.js' {
  declare module.exports: $Exports<'fs-transaction/build/filenameUtils'>;
}
declare module 'fs-transaction/build/fs-transaction.js' {
  declare module.exports: $Exports<'fs-transaction/build/fs-transaction'>;
}
declare module 'fs-transaction/build/sequencePromise.js' {
  declare module.exports: $Exports<'fs-transaction/build/sequencePromise'>;
}
declare module 'fs-transaction/src/errorTypes.js' {
  declare module.exports: $Exports<'fs-transaction/src/errorTypes'>;
}
declare module 'fs-transaction/src/filenameUtils.js' {
  declare module.exports: $Exports<'fs-transaction/src/filenameUtils'>;
}
declare module 'fs-transaction/src/fs-transaction.js' {
  declare module.exports: $Exports<'fs-transaction/src/fs-transaction'>;
}
declare module 'fs-transaction/src/sequencePromise.js' {
  declare module.exports: $Exports<'fs-transaction/src/sequencePromise'>;
}
